server:
  port: 8081
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mariadb://192.168.2.101:3306/sbdemo
    driver-class-name: org.mariadb.jdbc.Driver
    username: fly8604
    password: citic
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/
mybatis:
  mapper-locations: classpath:com/example/mapper/*.xml
  type-aliases-package: com.example.demo.domain
logging:
  config: classpath:logback-spring.xml

