server:
  port: 8081
  servlet:
    context-path: /demo
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.2.101:3306/sbdemo
    username: fly8604
    password: citic
    initialSize: 1
    minIdle: 1
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM CITY
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,slf4j
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/
mybatis:
  mapper-locations: classpath:com/example/mapper/*.xml
  type-aliases-package: com.example.demo.domain
pagehelper:
  helper-dialect: mariadb
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  path: classpath:logback-spring.xml


